### ISSUE TITLE
Code Louisville FEWD Track Courses to be Completed

### ISSUE THREAD

**Issue by chelseaniemeier** [chelseaniemeier/Treehouse#2]
## TODO

*Courses left to complete the CodeLouisville FEWD Track*

- [ ] GitHub Basics
- [ ] HTML Tables
- [ ] HTML Video and Audio
- [ ] Responsive Layouts
- [ ] AJAX Basics
- [ ] Bootstrap 4 Basics
- [ ] Accessibility
- [ ] Website Optimization
- [ ] Intro to Front End Performance Optimization
- [ ] Introduction to Design Patters

:tada: :ok_woman: :confetti_ball:
